exports.resolvers = {
  Query: {
    admin_dashboard_get: require("./resolver/query/admin").adminDashboardGet,
    admin_user_inspect_get: require("./resolver/query/admin").adminUserInspectGet,
    admin_user_report_get: require("./resolver/query/admin").adminUserReportGet,
    admin_dashboard_chart_list: require("./resolver/query/chart").listDashboardChart,
    admin_track_chart_list: require("./resolver/query/chart").listTrackChart,

    ana_login_history: require("./resolver/query/analysis").loginHistoryList,
    ana_grade_per_course: require("./resolver/query/analysis").courseGradeList,
    ana_meeting: require("./resolver/query/analysis").meetingTimeList,
    ana_module: require("./resolver/query/analysis").moduleTimeList,

    app_dashboard_get: require("./resolver/query/app").appDashboardGet,
    app_course_detail_get: require("./resolver/query/app").appCourseDetailGet,
    app_course_unit_get: require("./resolver/query/app").appCourseUnitGet,

    category_list: require("./resolver/query/category").categoryList,
    chat_list: require("./resolver/query/message").listChatHist,
    chat_user_list: require("./resolver/query/message").listChatUser,
    comment_list: require("./resolver/query/comment").listComment,
    comment_whole_list: require("./resolver/query/comment").listWholeComment,
    comment_recent_list: require("./resolver/query/comment").listRecentComment,
    comment_count: require("./resolver/query/comment").getCommentsNumber,
    coach_list: require("./resolver/query/coach").coachList,
    course_list: require("./resolver/query/course").listCourse,

    dashboard_get: require("./resolver/query/dashboard").dashboardGet,
    email_template_list: require("./resolver/query/email").emailTemplateList,
    email_log_list: require("./resolver/query/email").emailLogList,
    email_all_log_list: require("./resolver/query/email").emailAllLogList,
    group_list: require("./resolver/query/group").groupList,

    inspect_module_list: require("./resolver/query/module_inspect").listInspectModule,
    inspect_meeting_list: require("./resolver/query/meet_inspect").listMeetingInspect,
    inspect_vimeo_list: require("./resolver/query/vimeo_inspect").listInspectVimeo,
    inspect_vimeo_get: require("./resolver/query/vimeo_inspect").getInspectVimeo,
    inspect_replay_list: require("./resolver/query/replay_inspect").listReplayInspect,

    license_list: require("./resolver/query/license").licenseList,
    meeting_token_get: require("./resolver/query/meet_event").getMeetingToken,
    meeting_list: require("./resolver/query/meet_event").listMeeting,
    meeting_upcoming_list: require("./resolver/query/meet_event").listMeetingUpcoming,
    meet_recording_list: require("./resolver/query/meet_event").listMeetingRecording,

    master_dashboard_get: require("./resolver/query/master").masterDashboardGet,
    master_platform_list: require("./resolver/query/master").masterPlatformList,
    master_platform_get: require("./resolver/query/master").masterPlatformGet,
    master_platform_status_get: require("./resolver/query/master").masterPlatformStatusGet,

    physical_session_list: require("./resolver/query/physical_session").listPhysicalSession,
    physical_session_user_list: require("./resolver/query/physical_session").listPhysicalSessionUsers,

    search_list: require("./resolver/query/search").listSearch,
    send_survey_email: require("./resolver/query/email").sendSurveyEmail,
    send_email: require("./resolver/query/email").sendTestEmail,
    send_pwd_reset_email: require("./resolver/query/email").sendPasswordResetEmail,
    send_coach_email: require("./resolver/query/email").sendToCoachEmail,
    send_sms: require("./resolver/query/sms").sendTestSMS,
    sms_template_list: require("./resolver/query/sms").smsTemplateList,
    sms_log_list: require("./resolver/query/sms").smsLogList,

    theme_list: require("./resolver/query/theme").themeList,
    tutor_list: require("./resolver/query/tutor").tutorList,

    user_email_exist: require("./resolver/query/user").userEmailExist,
    user_ghost_token_get: require("./resolver/query/user").getGhostToken,
    user_login_log_list: require("./resolver/query/login_hist").listLoginHist,
    user_list: require("./resolver/query/user").userList,
    user_course_list: require("./resolver/query/user").userCourseList,
    user_send_reminders: require("./resolver/query/user").sentReminderToUsers,
    user_comment_list: require("./resolver/query/comment").listUserComment,
    user_chart_list: require("./resolver/query/chart").listUserTimeChart,

    z_query: require("./resolver/mutation/cron").updateMeetResults,
    z_pop: require("./resolver/query/pop").listPops,
  },
  Mutation: {
    category_edit: require("./resolver/mutation/category").editCategory,
    category_assign_courses: require("./resolver/mutation/category").assignCoursesToCategory,
    category_dismiss_courses: require("./resolver/mutation/category").dismissCoursesFromGroup,
    category_delete: require("./resolver/mutation/category").deleteCategory,

    chat_add: require("./resolver/mutation/message").addMessage,
    chat_edit: require("./resolver/mutation/message").editMessage,
    chat_delete_one: require("./resolver/mutation/message").deleteOneMessage,
    chat_delete_all: require("./resolver/mutation/message").deleteAllMessage,
    chat_flag_edit: require("./resolver/mutation/message").editChatFlag,
    chat_user_enabled: require("./resolver/mutation/message").changeChatUserStatus,

    certificate_create: require("./resolver/mutation/certificate").createCertificate,
    certificate_variable_edit: require("./resolver/mutation/certificate_variable").editCertificateVariable,
    clean_mongo_courses: require("./resolver/mutation/course").cleanMongoCourses,

    coach_edit: require("./resolver/mutation/coach").editCoach,
    coach_delete: require("./resolver/mutation/coach").deleteCoach,
    course_delete: require("./resolver/mutation/course").deleteCourse,
    course_info_edit: require("./resolver/mutation/course").editCourseAddition,

    comment_create: require("./resolver/mutation/comment").createComment,
    comment_edit: require("./resolver/mutation/comment").editComment,
    comment_third_edit: require("./resolver/mutation/comment").editThirdComment,
    comment_vote_edit: require("./resolver/mutation/comment").editCommentVote,
    comment_delete: require("./resolver/mutation/comment").deleteComment,

    email_template_edit: require("./resolver/mutation/email").editEmailTemplate,
    group_edit: require("./resolver/mutation/group").editGroup,
    group_assign_users: require("./resolver/mutation/group").assignUsersToGroup,
    group_dismiss_users: require("./resolver/mutation/group").dismissUsersFromGroup,
    group_assign_courses: require("./resolver/mutation/group").assignCoursesToGroup,
    group_dismiss_courses: require("./resolver/mutation/group").dismissCoursesFromGroup,
    group_delete: require("./resolver/mutation/group").deleteGroup,

    license_add: require("./resolver/mutation/license").addLicense,
    license_delete: require("./resolver/mutation/license").deleteLicense,

    master_platform_edit: require("./resolver/mutation/master").editPlatform,
    meeting_create: require("./resolver/mutation/meet_event").createMeeting,
    meeting_edit: require("./resolver/mutation/meet_event").editMeeting,
    meeting_delete: require("./resolver/mutation/meet_event").deleteMeeting,
    meeting_recording_create: require("./resolver/mutation/meet_event").insertMeetingRecording,
    meet_inspect_edit: require("./resolver/mutation/meet_inspect").updateMeetInspect,
    module_inspect_edit: require("./resolver/mutation/module_inspect").editInspectModule,

    user_edit: require("./resolver/mutation/user").editUser,
    user_login: require("./resolver/mutation/user").addLoginHistory,
    user_delete: require("./resolver/mutation/user").deleteUser,
    user_answer_edit: require("./resolver/mutation/student").editStudentAnswer,
    user_other_edit: require("./resolver/mutation/user").editRegisteredUser,
    user_other_pwd_edit: require("./resolver/mutation/user").editRegisteredUserPwd,
    user_register: require("./resolver/mutation/user").registerUser,
    user_bulk_register: require("./resolver/mutation/user").registerBulkUsers,
    user_assign_courses: require("./resolver/mutation/user").assignCoursesToUser,
    user_dismiss_courses: require("./resolver/mutation/user").dismissCoursesFromUser,
    user_enroll_update: require("./resolver/mutation/user").updateEnrollDates,
    user_forget_password: require("./resolver/mutation/user").resetPassword,

    physical_edit: require("./resolver/mutation/physical_session").editPhysicalSession,
    physical_assign_users: require("./resolver/mutation/physical_session").assignUsersToPhysicalSession,
    physical_dismiss_users: require("./resolver/mutation/physical_session").dismissUsersFromPhysicalSession,
    physical_delete: require("./resolver/mutation/physical_session").deletePhysicalSession,

    review_edit: require("./resolver/mutation/review").editReview,
    replay_inspect_edit: require("./resolver/mutation/replay_inspect").editReplayInspect,
    reset_platform: require("./resolver/mutation/reset").resetPlatform,

    sms_template_edit: require("./resolver/mutation/sms").editSMSTemplate,
    sync_course_differences: require("./resolver/mutation/course").syncCourseDifferences,

    term_edit: require("./resolver/mutation/terms").editTerms,
    theme_edit: require("./resolver/mutation/theme").editTheme,
    tutor_edit: require("./resolver/mutation/tutor").editTutor,
    tutor_delete: require("./resolver/mutation/tutor").deleteTutor,

    vimeo_inspect_edit: require("./resolver/mutation/vimeo_inspect").editInspectVimeo,

    z_mutation: require("./resolver/mutation/module_inspect").modifyModuleDBStructure,
    z_mutation1: require("./resolver/mutation/cron").syncCourseDifferencesFromDigital,
  },
};
