NODE_ENV: dev

REACT_APP_SITE_DISPLAY_NAME: Digital Learning Solution
REACT_APP_SITE_NAME: dev
REACT_APP_CONTACT_EMAIL: 

REACT_APP_BASE_URL: <domain>
REACT_APP_AUTH_ENDPOINT: <domain>/auth
REACT_APP_APP_ENDPOINT: <domain>/app
REACT_APP_ADMIN_ENDPOINT: <domain>/admin

REACT_APP_VIMEO_API_PUBLIC: 
REACT_APP_VIMEO_API_PRIVATE: 
REACT_APP_VIMEO_API_TOKEN: 

REACT_APP_S3_BUCKET_NAME: 
REACT_APP_S3_ACCESS_KEY: 
REACT_APP_S3_SECRET_KEY: 
REACT_APP_S3_REGION: 

REACT_APP_S3_DEV_BUCKET_NAME: 
REACT_APP_S3_DEV_ACCESS_KEY: 
REACT_APP_S3_DEV_SECRET_KEY: 

REACT_APP_PUSHER_API_ID: 
REACT_APP_PUSHER_KEY: 
REACT_APP_PUSHER_SECRET: 
REACT_APP_PUSHER_CLUSTER: 

REACT_APP_JITSI_APP_ID: 
REACT_APP_JITSI_API_KEY: 
REACT_APP_JITSI_DOMAIN: 

MYSQL_DB_IDENTIFIER: 
MYSQL_DB_NAME: 
MYSQL_DB_USERNAME: 
MYSQL_DB_PASSWORD: 
MYSQL_DB_HOST: 
MYSQL_DB_PORT: 

MONGO_DB_MAIN_NAME: 
MONGO_DB_MAIN_USERNAME: 
MONGO_DB_MAIN_PASSWORD: 
MONGO_DB_MAIN_HOST: 
MONGO_DB_MAIN_PORT: 

MONGO_DB_FORUM_NAME: 
MONGO_DB_FORUM_USERNAME: 
MONGO_DB_FORUM_PASSWORD: 
MONGO_DB_FORUM_HOST: 
MONGO_DB_FORUM_PORT: 

MONGO_DB_INSPECT_NAME: 
MONGO_DB_INSPECT_USERNAME: 
MONGO_DB_INSPECT_PASSWORD: 
MONGO_DB_INSPECT_HOST: 
MONGO_DB_INSPECT_PORT: 

SMTP_USERNAME: 
SMTP_PASSWORD: 
SMTP_HOST: 
SMTP_FROM: 

TEST_PWD_HASH: 
GOOGLE_CALENDAR_ID: 
REACT_APP_TEST_JWT_TOKEN: 
